language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  #- rbx-19mode
  #- rbx-head
before_install:
  - sudo apt-get install libraptor2-0
  - sudo ln -s /usr/lib/libraptor2.so.0 /usr/lib/libraptor2.so
  - bundle install
  - gem list
#bundler_args: --without development
